name: Astronomer CI - Deploy dbt code

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.9.0
      with:
            deployment-id: cm7suoy2a18wr01r7f2jhwtrq
            deploy-type: dbt
            root-folder: dbt/my_simple_dbt_project
