name: Astronomer CI - Deploy dbt code

on:
  push:
    branches:
      - dbt-only
  
env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dbt-only branch
      uses: actions/checkout@v4
      with:
        ref: dbt-only
        fetch-depth: 0 # Ensure full history is fetched

    - name: Deploy to Astro
      id: deploy
      uses: astronomer/deploy-action@v0.10.0
      with:
        deployment-id: cm7ubshgs0ahx01pb7afr8v12
        deploy-type: dbt
        root-folder: dbt/my_simple_dbt_project
        mount-path: /tmp/my_simple_dbt_project

    - name: Add test variable to GitHub output
      id: test_output
      run: |
        echo "TEST_VARIABLE=HelloWorld" >> $GITHUB_OUTPUT

    - name: Show deploy outputs
      run: |
        echo "DBT_DEPLOY=${{ steps.deploy.outputs.DBT_DEPLOY }}"
        echo "DBT_OPTIONS=${{ steps.deploy.outputs.DBT_OPTIONS }}"
        echo "TEST_VARIABLE=${{ steps.test_output.outputs.TEST_VARIABLE }}"

    - name: Debug all outputs
      run: |
        echo "==== ALL OUTPUTS ===="
        echo '${{ toJSON(steps) }}' | jq
